server:
  port: 8006
spring:
  application:
    name: aps-server
  #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

pac4j:
  callbackUrl: http://localhost:8006/callback
  clientsProperties:
    github.id: 962983273f05590ba725
    github.secret: fc95ba172cec788571b64c58d79e4138e7f494b9
  securityConstraints:
    - clientName: githubclient
      roleAndPermissions:
        roleMapping: {admin: test,ss: dd}
        permissionMapping: {ee:tt}
  tokenGenerate: Jwt
